version: "3"

services:
  video-analyzer:
    build:
      context: ./video-analyzer-api
    ports:
      - "8000:8000"
    volumes:
      - ./shared-data:/app/shared-data
      - ./video-analyzer-api/app:/app/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
