services:
  video-analyzer:
    build:
      context: ./video-analyzer-api
    ports:
      - "8000:8000"
    env_file:
      - ./video-analyzer-api/.env
    volumes:
      - ./shared-data:/app/shared-data
      - ./video-analyzer-api/app:/app/app
      - ./video-analyzer-api/scripts:/app/scripts
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["python3", "scripts/check_models.py"]
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
